"""HabitRepository protocol."""
from __future__ import annotations

from datetime import date
from typing import Protocol, runtime_checkable

from src.domain.entities.habit import Habit
from src.domain.entities.habit_log import HabitLog


@runtime_checkable
class HabitRepository(Protocol):
    async def add(self, habit: Habit) -> Habit: ...
    async def get(self, habit_id: int) -> Habit | None: ...
    async def list_for_user(self, user_id: int, active_only: bool = True) -> list[Habit]: ...
    async def deactivate(self, habit_id: int, user_id: int) -> None: ...
    async def update(self, habit: Habit) -> Habit | None: ...
    async def list_expired_goals(self, today: date) -> list[Habit]: ...


@runtime_checkable
class HabitLogRepository(Protocol):
    async def upsert(self, log: HabitLog) -> None: ...
    async def get_for_date(self, habit_id: int, log_date: date) -> HabitLog | None: ...
    async def list_for_habit(self, habit_id: int, since: date) -> list[HabitLog]: ...
    async def list_completed_dates(self, habit_id: int) -> list[date]: ...
    async def list_for_user_in_range(self, user_id: int, since: date, until: date) -> list[HabitLog]: ...
    async def today_status(self, user_id: int, today: date) -> list[tuple[Habit, bool]]: ...
